site_name: e-lims-d2xx
site_url: https://fabienmeyer.github.io//e-lims-d2xx
site_description: Cookiecutter template for e-lims projects
site_author: Fabien Meyer
site_dir: build
watch: [mkdocs.yml, docs, CHANGELOG.md, CODE_OF_CONDUCT.md, CONTRIBUTING.md, LICENSE, README.md]

theme:
  name: material
  language: en
  features:
    - content.code.select
    - content.code.copy
  palette: 
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav: # Setting up the navigation. Te below list will be tabs on left panel
  - Home: index.md
  - Changelog: changelog.md
  - Contributing: contributing.md
  - Code of Conduct: code_of_conduct.md
  - License: license.md

markdown_extensions:
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
plugins:
  - privacy

extra:
  consent:
    cookies:
      analytics: Google Analytics
      github: GitHub 
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    copyright: >
      Copyright &copy; 2024 Fabien Meyer –
      <a href="#__consent">Change cookie settings</a>
    actions:
      - accept
      - reject
